import type { Scenario } from '../types/game';

/** Offline fallback scenarios in case Supabase is unavailable */
export const fallbackScenarios: Scenario[] = [
  { id: 'local-1', text: 'Pineapple on pizza', category: 'food' },
  { id: 'local-2', text: 'Monday mornings', category: 'lifestyle' },
  { id: 'local-3', text: 'Getting caught in the rain', category: 'experiences' },
  { id: 'local-4', text: 'Reality TV shows', category: 'entertainment' },
  { id: 'local-5', text: 'Sleeping with socks on', category: 'lifestyle' },
  { id: 'local-6', text: 'Cold showers', category: 'lifestyle' },
  { id: 'local-7', text: 'Public speaking', category: 'experiences' },
  { id: 'local-8', text: 'Parallel parking', category: 'skills' },
  { id: 'local-9', text: 'Rollercoasters', category: 'experiences' },
  { id: 'local-10', text: 'Eating cereal for dinner', category: 'food' },
  { id: 'local-11', text: 'Working from home', category: 'lifestyle' },
  { id: 'local-12', text: 'Small talk with strangers', category: 'social' },
  { id: 'local-13', text: 'Camping in a tent', category: 'experiences' },
  { id: 'local-14', text: 'Karaoke night', category: 'entertainment' },
  { id: 'local-15', text: 'Being the designated driver', category: 'social' },
  { id: 'local-16', text: 'Waking up early on weekends', category: 'lifestyle' },
  { id: 'local-17', text: 'Spicy food', category: 'food' },
  { id: 'local-18', text: 'Long car rides', category: 'experiences' },
  { id: 'local-19', text: 'Group photos', category: 'social' },
  { id: 'local-20', text: 'Doing laundry', category: 'lifestyle' },
  { id: 'local-21', text: 'Going to the dentist', category: 'experiences' },
  { id: 'local-22', text: 'Surprise parties', category: 'social' },
  { id: 'local-23', text: 'Black licorice', category: 'food' },
  { id: 'local-24', text: 'Airport layovers', category: 'experiences' },
  { id: 'local-25', text: 'Assembling IKEA furniture', category: 'lifestyle' },
  { id: 'local-26', text: 'Hot yoga', category: 'fitness' },
  { id: 'local-27', text: 'Board game nights', category: 'entertainment' },
  { id: 'local-28', text: 'Running in the morning', category: 'fitness' },
  { id: 'local-29', text: 'Blind dates', category: 'social' },
  { id: 'local-30', text: 'Instant ramen', category: 'food' },
  { id: 'local-31', text: 'Traffic jams', category: 'experiences' },
  { id: 'local-32', text: 'Thunderstorms', category: 'nature' },
  { id: 'local-33', text: 'Pop music', category: 'entertainment' },
  { id: 'local-34', text: 'Sushi', category: 'food' },
  { id: 'local-35', text: 'Winter holidays', category: 'seasonal' },
  { id: 'local-36', text: 'Early flights', category: 'experiences' },
  { id: 'local-37', text: 'Movie sequels', category: 'entertainment' },
  { id: 'local-38', text: 'Buffets', category: 'food' },
  { id: 'local-39', text: 'Team building exercises', category: 'work' },
  { id: 'local-40', text: 'Social media', category: 'lifestyle' },
];
